services:
  prometheus:
    image: prom/prometheus:v2.53.0
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  node-exporter:
    image: prom/node-exporter:master
    ports:
      - 9100:9100

  grafana:
    image: grafana/grafana-enterprise
    ports:
      - 3000:3000
    environment:
      # https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#override-configuration-with-environment-variables
      - GF_LOG_LEVEL=debug
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-hunter123}
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER:-hunter}
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-polystat-panel
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:
