services:
  prometheus:
    image: prom/prometheus:v2.53.0
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/rules.yml:/etc/prometheus/rules.yml
    ports:
      - 9090:9090

  node-exporter:
    image: prom/node-exporter:master
    ports:
      - 9100:9100

  grafana:
    image: grafana/grafana-enterprise
    ports:
      - 3000:3000
    environment:
      # https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#override-configuration-with-environment-variables
      - GF_LOG_LEVEL=debug
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-hunter123}
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER:-hunter}
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-polystat-panel
    volumes:
      - grafana-data:/var/lib/grafana

  # this contains the prom middleware infront of the express application to capture metrics related to http request
  prom-middleware:
    build:
      context: prom_middleware
    environment:
      - PORT=3001
      - HOST=0.0.0.0
    ports:
      - 3001:3001
    volumes:
      - ./prom_middleware:/app
      - /app/node_modules

  github-exporter:
    image: githubexporter/github-exporter:latest
    ports:
      - 9171:9171
    environment:
      - LOG_LEVEL=debug
      - LISTEN_PORT=9171
      - REPOS=prometheus/prometheus
      - GITHUB_TOKEN=${GITHUB_TOKEN}

  alert-manager:
    image: prom/alertmanager:main
    volumes:
      - ./prometheus/alert_manager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    environment:
      - WEBHOOK_URL=${WEBHOOK_URL}
    ports:
      - 9093:9093

  mailpit:
    image: axllent/mailpit
    environment:
      - MP_SMTP_AUTH_ALLOW_INSECURE=1
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  grafana-data:
