global:
  scrape_interval: "15s"
  scrape_timeout: "10s"
  evaluation_interval: "15s"

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: "prometheus"
    # specify the static targets that prometheus should scrape
    # will look into /metrics path on these targets
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "prom-middleware"
    scrape_interval: 5s
    static_configs:
      - targets: ["prom-middleware:3001"]

  - job_name: "github-exporter"
    scrape_interval: 5m
    static_configs:
      - targets: ["github-exporter:9171"]
